'use strict';
const escape=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[c])).replace(/[\x00-\x08\x0b\x0c\x0e-\x1f]/g,'');
const money=c=>(c/100).toFixed(2);
function amounts(lines){const net=lines.reduce((n,l)=>n+Math.round(Math.abs(l.grossCents)*100/(100+l.vatRate)),0),gross=lines.reduce((n,l)=>n+Math.abs(l.grossCents),0);const tax=Math.round(net*19/100);return {net,tax,gross,rounding:gross-net-tax};}
function renderInvoiceXml(s){
 const paymentAccount=s.bankTransfer?.bankAccount||s.issuer.iban,paymentReference=s.bankTransfer?.transferReference||s.number;
 const credit=s.kind==='credit',root=credit?'CreditNote':'Invoice',lineTag=credit?'CreditNoteLine':'InvoiceLine',qtyTag=credit?'CreditedQuantity':'InvoicedQuantity';
 if(!s.buyer?.name||!s.buyer?.address||!s.buyer?.postalCode||!s.buyer?.city)throw Error('Vollständige Rechnungsanschrift erforderlich.');
 if(s.lines.some(l=>l.vatRate!==19||!Number.isSafeInteger(l.grossCents)))throw Error('Nicht unterstützte Steuer- oder Betragsangabe.');
 const sum=amounts(s.lines),date=d=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Berlin',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(d)),a=(tag,c)=>'<cbc:'+tag+' currencyID="EUR">'+money(c)+'</cbc:'+tag+'>';
 const address=p=>'<cac:PostalAddress><cbc:StreetName>'+escape(p.address)+'</cbc:StreetName><cbc:CityName>'+escape(p.city)+'</cbc:CityName><cbc:PostalZone>'+escape(p.postalCode)+'</cbc:PostalZone><cac:Country><cbc:IdentificationCode>DE</cbc:IdentificationCode></cac:Country></cac:PostalAddress>';
 const taxId=String(s.issuer.taxId).replace(/\s/g,''),taxScheme=/^DE[0-9]{9}$/.test(taxId)?'VAT':'FC';
 const taxCategory='<cac:TaxCategory><cbc:ID>S</cbc:ID><cbc:Percent>19</cbc:Percent><cac:TaxScheme><cbc:ID>VAT</cbc:ID></cac:TaxScheme></cac:TaxCategory>';
 const note=(s.depositCents&&!credit?'Rückzahlbare Sicherheitsleistung (Kaution), separat und ohne Umsatzsteuer: '+money(s.depositCents)+' EUR. Gemeinsam mit der Miete zu zahlender Gesamtbetrag: '+money(sum.gross+s.depositCents)+' EUR. ':'')+(s.paidAt?'Zahlung bereits erhalten.':s.kind==='credit'?'Rechnungskorrektur; Erstattung über den ursprünglichen Zahlungsweg.':s.scope==='additional'?'Separate Nachzahlung innerhalb von 14 Tagen überweisen.':'Miete und Kaution gemeinsam innerhalb von 14 Tagen überweisen.');
 return '<?xml version="1.0" encoding="UTF-8"?>\n<'+root+' xmlns="urn:oasis:names:specification:ubl:schema:xsd:'+root+'-2" xmlns:cac="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2" xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2">'+
 '<cbc:CustomizationID>urn:cen.eu:en16931:2017</cbc:CustomizationID><cbc:ID>'+escape(s.number)+'</cbc:ID><cbc:IssueDate>'+date(s.issuedAt)+'</cbc:IssueDate>'+(!credit?'<cbc:DueDate>'+date(s.dueAt)+'</cbc:DueDate>':'')+'<cbc:'+root+'TypeCode>'+(credit?'381':'380')+'</cbc:'+root+'TypeCode><cbc:Note>'+escape(note)+'</cbc:Note><cbc:DocumentCurrencyCode>EUR</cbc:DocumentCurrencyCode>'+
 '<cac:OrderReference><cbc:ID>'+escape(s.orderNo)+'</cbc:ID></cac:OrderReference>'+(credit?'<cac:BillingReference><cac:InvoiceDocumentReference><cbc:ID>'+escape(s.originalNumber)+'</cbc:ID><cbc:IssueDate>'+date(s.originalDate)+'</cbc:IssueDate></cac:InvoiceDocumentReference></cac:BillingReference>':'')+
 '<cac:AccountingSupplierParty><cac:Party>'+address(s.issuer)+'<cac:PartyTaxScheme><cbc:CompanyID>'+escape(taxId)+'</cbc:CompanyID><cac:TaxScheme><cbc:ID>'+taxScheme+'</cbc:ID></cac:TaxScheme></cac:PartyTaxScheme><cac:PartyLegalEntity><cbc:RegistrationName>'+escape(s.issuer.name)+'</cbc:RegistrationName></cac:PartyLegalEntity><cac:Contact><cbc:ElectronicMail>'+escape(s.issuer.email)+'</cbc:ElectronicMail></cac:Contact></cac:Party></cac:AccountingSupplierParty>'+
 '<cac:AccountingCustomerParty><cac:Party>'+address(s.buyer)+'<cac:PartyLegalEntity><cbc:RegistrationName>'+escape(s.buyer.name)+'</cbc:RegistrationName></cac:PartyLegalEntity></cac:Party></cac:AccountingCustomerParty>'+
 '<cac:PaymentMeans><cbc:PaymentMeansCode>'+(paymentAccount?'30':'1')+'</cbc:PaymentMeansCode><cbc:PaymentID>'+escape(paymentReference)+'</cbc:PaymentID>'+(paymentAccount?'<cac:PayeeFinancialAccount><cbc:ID>'+escape(paymentAccount)+'</cbc:ID><cbc:Name>'+escape(s.bankTransfer?'Mollie':s.issuer.accountHolder||s.issuer.name)+'</cbc:Name></cac:PayeeFinancialAccount>':'')+'</cac:PaymentMeans>'+
 '<cac:PaymentTerms><cbc:Note>'+escape(credit?'Erstattung über ursprüngliches Zahlungsmittel.':s.scope==='additional'?'14 Tage ab Rechnungsdatum; eigenständige Nachzahlung.':'14 Tage ab Rechnungsdatum; gemeinsame Zahlung von Miete und Kaution.')+'</cbc:Note></cac:PaymentTerms>'+
 '<cac:TaxTotal>'+a('TaxAmount',sum.tax)+'<cac:TaxSubtotal>'+a('TaxableAmount',sum.net)+a('TaxAmount',sum.tax)+taxCategory+'</cac:TaxSubtotal></cac:TaxTotal>'+
 '<cac:LegalMonetaryTotal>'+a('LineExtensionAmount',sum.net)+a('TaxExclusiveAmount',sum.net)+a('TaxInclusiveAmount',sum.net+sum.tax)+(s.paidAt&&!credit?a('PrepaidAmount',sum.gross):'')+(sum.rounding?a('PayableRoundingAmount',sum.rounding):'')+a('PayableAmount',s.paidAt&&!credit?0:sum.gross)+'</cac:LegalMonetaryTotal>'+
 s.lines.map((l,i)=>{const net=Math.round(Math.abs(l.grossCents)*100/(100+l.vatRate)),qty=l.quantity||1;return '<cac:'+lineTag+'><cbc:ID>'+(i+1)+'</cbc:ID><cbc:'+qtyTag+' unitCode="DAY">'+qty+'</cbc:'+qtyTag+'>'+a('LineExtensionAmount',net)+(l.period?'<cac:InvoicePeriod><cbc:StartDate>'+escape(l.period.slice(0,10))+'</cbc:StartDate><cbc:EndDate>'+escape(l.period.slice(-10))+'</cbc:EndDate></cac:InvoicePeriod>':'')+'<cac:Item><cbc:Name>'+escape(l.description)+'</cbc:Name><cac:ClassifiedTaxCategory><cbc:ID>S</cbc:ID><cbc:Percent>19</cbc:Percent><cac:TaxScheme><cbc:ID>VAT</cbc:ID></cac:TaxScheme></cac:ClassifiedTaxCategory></cac:Item><cac:Price><cbc:PriceAmount currencyID="EUR">'+(net/100/qty).toFixed(8)+'</cbc:PriceAmount></cac:Price></cac:'+lineTag+'>';}).join('')+'</'+root+'>';
}
module.exports={renderInvoiceXml,amounts};
