CREATE TABLE contract_declarations (
    id CHAR(36) NOT NULL,
    payload_hash CHAR(64) NOT NULL,
    kind VARCHAR(20) NOT NULL,
    customer_name VARCHAR(200) NOT NULL,
    customer_email VARCHAR(255) NOT NULL,
    contract_reference VARCHAR(200) NOT NULL,
    contract_scope TEXT NOT NULL,
    declaration_text TEXT NOT NULL,
    received_at DATETIME(3) NOT NULL,
    order_id INT NULL,
    processing_status VARCHAR(30) NOT NULL DEFAULT 'received',
    processing_note TEXT NULL,
    processed_at DATETIME NULL,
    processed_by VARCHAR(255) NULL,
    confirmation_token_hash CHAR(64) NULL,
    confirmation_expires_at DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uq_declaration_confirmation (confirmation_token_hash),
    KEY idx_declaration_status_received (processing_status, received_at),
    KEY idx_declaration_order (order_id),
    CONSTRAINT fk_declaration_order FOREIGN KEY (order_id) REFERENCES rental_orders (id) ON DELETE SET NULL,
    CONSTRAINT chk_declaration_kind CHECK (kind IN ('withdrawal', 'cancellation'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
