CREATE TABLE IF NOT EXISTS mollie_invoice_settings (
 id TINYINT UNSIGNED NOT NULL PRIMARY KEY,
 test_recipient_email VARCHAR(254) NOT NULL DEFAULT '',
 revision INT UNSIGNED NOT NULL DEFAULT 1,
 updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
